export const data = [
    { id: 1, sports_name: 'Basketball' },
    { id: 2, sports_name: 'Football' },
    { id: 3, sports_name: 'Tennis' },
    { id: 4, sports_name: 'Baseball' },
    { id: 5, sports_name: 'Soccer' },
    { id: 6, sports_name: 'Golf' },
    { id: 7, sports_name: 'Rugby' },
    { id: 8, sports_name: 'Cricket' },
    { id: 9, sports_name: 'Hockey' },
    { id: 10, sports_name: 'Volleyball' },
    { id: 11, sports_name: 'Table Tennis' },
    { id: 12, sports_name: 'Badminton' },
    { id: 13, sports_name: 'Swimming' },
    { id: 14, sports_name: 'Boxing' },
    { id: 15, sports_name: 'Wrestling' },
    { id: 16, sports_name: 'Cycling' },
    { id: 17, sports_name: 'Gymnastics' },
    { id: 18, sports_name: 'Karate' },
    { id: 19, sports_name: 'Surfing' },
    { id: 20, sports_name: 'Skateboarding' },
    { id: 21, sports_name: 'Equestrian' },
    { id: 22, sports_name: 'Judo' },
    { id: 23, sports_name: 'Taekwondo' },
    { id: 24, sports_name: 'Archery' },
    { id: 25, sports_name: 'Shooting' },
    { id: 26, sports_name: 'Rowing' },
    { id: 27, sports_name: 'Canoeing' },
    { id: 28, sports_name: 'Sailing' },
    { id: 29, sports_name: 'Triathlon' },
    { id: 30, sports_name: 'Weightlifting' },
    { id: 31, sports_name: 'Fencing' },
    { id: 32, sports_name: 'Diving' },
    { id: 33, sports_name: 'Water Polo' },
    { id: 34, sports_name: 'Handball' },
    { id: 35, sports_name: 'BMX Racing' },
    { id: 36, sports_name: 'Mountain Biking' },
    { id: 37, sports_name: 'Paralympic Sports' },
    { id: 38, sports_name: 'Skating' },
    { id: 39, sports_name: 'Snowboarding' },
    { id: 40, sports_name: 'Luge' },
    { id: 41, sports_name: 'Bobsleigh' },
    { id: 42, sports_name: 'Skeleton' },
    { id: 43, sports_name: 'Cross-country Skiing' },
    { id: 44, sports_name: 'Ski Jumping' },
    { id: 45, sports_name: 'Biathlon' },
    { id: 46, sports_name: 'Nordic Combined' },
    { id: 47, sports_name: 'Ice Hockey' },
    { id: 48, sports_name: 'Figure Skating' },
    { id: 49, sports_name: 'Speed Skating' },
    { id: 50, sports_name: 'Curling' },
];
