export const details = [
    { 
        id: 1, 
        sports_name: 'Basketball',
        description: 'A team sport where two teams try to score points by throwing a ball through the opposing team\'s hoop.',
        tickets: 'Available',
        series: 'NBA',
        matches: 82,
        images: ['https://i.pinimg.com/originals/ab/56/0f/ab560f878e82c3f9ec3e9b7ec7b75668.jpg'],
    },
    { 
        id: 2, 
        sports_name: 'Football',
        description: 'A team sport played with a spherical ball between two teams of eleven players.',
        tickets: 'Sold Out',
        series: 'Premier League',
        matches: 38,
        images: ['https://i.pinimg.com/originals/ae/6c/eb/ae6ceb03899cb99c6937b02070e2c943.jpg'],
    },
    { 
        id: 3, 
        sports_name: 'Tennis',
        description: 'A racket sport that can be played individually against a single opponent or between two teams of two players each.',
        tickets: 'Available',
        series: 'ATP Tour',
        matches: 77,
        images: ['https://i.pinimg.com/originals/47/f6/10/47f6108f75da4cf32ef76144b5c26d04.jpg'],
    },
    { 
        id: 4, 
        sports_name: 'Baseball',
        description: 'A bat-and-ball game played between two teams of nine players.',
        tickets: 'Available',
        series: 'MLB',
        matches: 162,
        images: ['https://i.pinimg.com/originals/b9/12/af/b912afcb888b2ac0c60b2b648ff63c86.jpg'],
    },
    { 
        id: 5, 
        sports_name: 'Soccer',
        description: 'A team sport played between two teams of eleven players with a spherical ball.',
        tickets: 'Available',
        series: 'FIFA World Cup',
        matches: 64,
        images: ['https://i.pinimg.com/originals/3d/57/a0/3d57a0a86f9736a0f5d832c9a93b6d84.jpg'],
    },
    { 
        id: 6, 
        sports_name: 'Golf',
        description: 'A club-and-ball sport where players use clubs to hit balls into a series of holes on a course.',
        tickets: 'Available',
        series: 'PGA Tour',
        matches: 4,
        images: ['https://i.pinimg.com/originals/c7/62/6c/c7626c72f1aef640dcb3b26dbb4f5c1a.jpg'],
    },
    { 
        id: 7, 
        sports_name: 'Rugby',
        description: 'A team sport that involves carrying, passing, kicking, and grounding the ball to score points.',
        tickets: 'Available',
        series: 'Rugby World Cup',
        matches: 48,
        images: ['https://i.pinimg.com/originals/d0/61/3b/d0613bd6aa44e8454b7a9c8922b4f05f.jpg'],
    },
    { 
        id: 8, 
        sports_name: 'Cricket',
        description: 'A bat-and-ball game played between two teams of eleven players on a field.',
        tickets: 'Available',
        series: 'IPL',
        matches: 60,
        images: ['/assets/cri.jpg'],
    },
    { 
        id: 9, 
        sports_name: 'Hockey',
        description: 'A team sport played on ice or field with sticks and a puck or ball.',
        tickets: 'Available',
        series: 'NHL',
        matches: 82,
        images: ['https://i.pinimg.com/originals/3b/27/03/3b27030669c7a52807a37439b5f69373.jpg'],
    },
    { 
        id: 10, 
        sports_name: 'Volleyball',
        description: 'A team sport in which two teams try to score points by hitting a ball over a net.',
        tickets: 'Available',
        series: 'FIVB World Championship',
        matches: 24,
        images: ['https://i.pinimg.com/originals/8d/fb/37/8dfb372d3b4d0fd029aa6f96e7da2048.jpg'],
    },
    { 
        id: 11, 
        sports_name: 'Table Tennis',
        description: 'A racket sport played on a table divided by a net.',
        tickets: 'Available',
        series: 'ITTF World Tour',
        matches: 32,
        images: ['https://i.pinimg.com/originals/45/69/b5/4569b5b63654662ae09c9006b885b7d2.jpg'],
    },
    { 
        id: 12, 
        sports_name: 'Badminton',
        description: 'A racquet sport played using rackets to hit a shuttlecock across a net.',
        tickets: 'Available',
        series: 'BWF World Championships',
        matches: 26,
        images: ['https://i.pinimg.com/originals/d8/89/a1/d889a13562e9f320676cbd2e6d65eaa1.jpg'],
    },
    { 
        id: 13, 
        sports_name: 'Swimming',
        description: 'An individual or team racing sport that requires the use of one',
        tickets: 'Available',
        series: 'Olympic Games',
        matches: 32,
        images: ['https://i.pinimg.com/originals/ae/f1/10/aef1100e23f9c1d9d8e4f5c84554103f.jpg'],
    },
    { 
        id: 14, 
        sports_name: 'Boxing',
        description: 'A combat sport in which two people throw punches at each other for a predetermined amount of time.',
        tickets: 'Available',
        series: 'WBC',
        matches: 12,
        images: ['https://i.pinimg.com/originals/6d/31/64/6d3164cd6f6be5e5d22e0b038c63d1c2.jpg'],
    },
    { 
        id: 15, 
        sports_name: 'Wrestling',
        description: 'A combat sport involving grappling and techniques such as clinch fighting, throws, takedowns, joint locks, pins, and other holds.',
        tickets: 'Available',
        series: 'WWE',
        matches: 8,
        images: ['https://i.pinimg.com/originals/44/9c/b3/449cb3b103feff23a653d7a1ebc568f.jpg'],
    },
    { 
        id: 16, 
        sports_name: 'Cycling',
        description: 'A sport that involves riding bicycles, either for leisure, competition, or transportation.',
        tickets: 'Available',
        series: 'Tour de France',
        matches: 21,
        images: ['https://i.pinimg.com/originals/b0/47/1a/b0471aa97fc36d6381f29bdbf3440c3f.jpg'],
    },
    { 
        id: 17, 
        sports_name: 'Gymnastics',
        description: 'A sport that involves exercises and performances requiring physical strength, flexibility, balance, and coordination.',
        tickets: 'Available',
        series: 'Olympic Games',
        matches: 16,
        images: ['https://i.pinimg.com/originals/37/54/c7/3754c706a1d163c49307b7e49bc0e538.jpg'],
    },
    { 
        id: 18, 
        sports_name: 'Karate',
        description: 'A martial art developed in the Ryukyu Kingdom that emphasizes striking techniques.',
        tickets: 'Available',
        series: 'WKF World Championships',
        matches: 8,
        images: ['https://i.pinimg.com/originals/9e/ae/44/9eae4454c2f02db1e5ae9c1aa2b17c62.jpg'],
    },
    { 
        id: 19, 
        sports_name: 'Surfing',
        description: 'A water sport in which the participant rides on the forward section or swell of a moving wave.',
        tickets: 'Available',
        series: 'World Surf League',
        matches: 12,
        images: ['https://i.pinimg.com/originals/78/d2/f4/78d2f4969e8b188b6cc4640630dc844d.jpg'],
    },
    { 
        id: 20, 
        sports_name: 'Skiing',
        description: 'A recreational activity and competitive winter sport in which the participant uses skis to glide on snow.',
        tickets: 'Available',
        series: 'FIS World Cup',
        matches: 25,
        images: ['https://i.pinimg.com/originals/3b/d1/c2/3bd1c2dc43b34d944f6c74cb1cf90e1d.jpg'],
    },
    { 
        id: 21, 
        sports_name: 'Ice Skating',
        description: 'The act of moving on ice using ice skates, which are shoes with a metal blade on the bottom.',
        tickets: 'Available',
        series: 'ISU Championships',
        matches: 10,
        images: ['https://i.pinimg.com/originals/f9/5c/75/f95c75af89103e1a5f3a8a6da60c8ed7.jpg'],
    },
    { 
        id: 22, 
        sports_name: 'Motorsport',
        description: 'A term used to encompass the group of competitive events that primarily involve the use of motorized vehicles.',
        tickets: 'Available',
        series: 'Formula 1',
        matches: 22,
        images: ['https://i.pinimg.com/originals/66/15/d3/6615d3c21ac3d33fd6e676ffcf56804a.jpg'],
    },
    { 
        id: 23, 
        sports_name: 'Lacrosse',
        description: 'A team sport played with a small rubber ball and a long-handled stick called a crosse.',
        tickets: 'Available',
        series: 'NLL',
        matches: 18,
        images: ['https://i.pinimg.com/originals/ba/ba/64/baba64bafcd761c772af97d7d4d24979.jpg'],
    },
    { 
        id: 24, 
        sports_name: 'Field Hockey',
        description: 'A team game of hockey played on grass or artificial turf with curved sticks and a small hard ball.',
        tickets: 'Available',
        series: 'Hockey World Cup',
        matches: 44,
        images: ['https://i.pinimg.com/originals/9f/7d/06/9f7d0667dc1e22f5b1156e00fbaad5a0.jpg'],
    },
    { 
        id: 25, 
        sports_name: 'Netball',
        description: 'A team game derived from basketball, played on a rectangular court divided into thirds.',
        tickets: 'Available',
        series: 'Netball World Cup',
        matches: 16,
        images: ['https://i.pinimg.com/originals/f3/3f/c3/f33fc39bca9ab388df7dcaa5de03439f.jpg'],
    },
    { 
        id: 26, 
        sports_name: 'Handball',
        description: 'A team sport in which two teams pass a ball using their hands with the aim of throwing it into the goal of the other team.',
        tickets: 'Available',
        series: 'IHF World Championships',
        matches: 12,
        images: ['https://i.pinimg.com/originals/63/2d/0e/632d0e1b2e72f663d4d7c7f929bfc51b.jpg'],
    },
    { 
        id: 27, 
        sports_name: 'Fencing',
        description: 'A combat sport involving the use of swords in a competition.',
        tickets: 'Available',
        series: 'FIE World Championships',
        matches: 20,
        images: ['https://i.pinimg.com/originals/5d/b8/55/5db85595e98855403f3d1186e5f08cb7.jpg'],
    },
    { 
        id: 28, 
        sports_name: 'Ultimate Frisbee',
        description: 'A non-contact team sport played with a flying disc, combining elements of soccer, basketball, and football.',
        tickets: 'Available',
        series: 'USA Ultimate Championships',
        matches: 10,
        images: ['https://i.pinimg.com/originals/f3/ff/7f/f3ff7f9fa34f88cf205751b99a378058.jpg'],
    },
    { 
        id: 29, 
        sports_name: 'Water Polo',
        description: 'A team water sport consisting of four quarters where the objective is to score by throwing the ball into the opposing team\'s goal.',
        tickets: 'Available',
        series: 'FINA World Championships',
        matches: 16,
        images: ['https://i.pinimg.com/originals/c0/82/1c/c0821cfa4d80f4c96383bc353bcf4aa7.jpg'],
    },
    { 
        id: 30, 
        sports_name: 'Rugby Sevens',
        description: 'A variant of rugby union where teams are made up of seven players and games are shorter.',
        tickets: 'Available',
        series: 'Rugby Sevens World Series',
        matches: 10,
        images: ['https://i.pinimg.com/originals/c4/34/5f/c4345f675ee1b1292df4df51ca1b1b70.jpg'],
    },
    { 
        id: 31, 
        sports_name: 'Dodgeball',
        description: 'A team sport in which players on two teams try to hit opponents with a ball.',
        tickets: 'Available',
        series: 'Dodgeball World Championship',
        matches: 6,
        images: ['https://i.pinimg.com/originals/8b/78/6d/8b786d18695d062f8ac45c9b167918a1.jpg'],
    },
    { 
        id: 32, 
        sports_name: 'Billiards',
        description: 'A cue sport played on a rectangular table with pockets, where the goal is to score points by shooting balls into the pockets.',
        tickets: 'Available',
        series: 'World Pool-Billiard Association',
        matches: 16,
        images: ['https://i.pinimg.com/originals/8f/9c/09/8f9c09b3543780f4a827e06bc5f94251.jpg'],
    },
    { 
        id: 33, 
        sports_name: 'Rock Climbing',
        description: 'An activity in which participants climb up, down, or across natural rock formations or artificial rock walls.',
        tickets: 'Available',
        series: 'IFSC World Cup',
        matches: 5,
        images: ['https://i.pinimg.com/originals/0b/14/44/0b14448e06f3680be3df6fa99eec7818.jpg'],
    },
    { 
        id: 34, 
        sports_name: 'CrossFit',
        description: 'A high-intensity fitness training program incorporating elements from several sports and types of exercise.',
        tickets: 'Available',
        series: 'CrossFit Games',
        matches: 4,
        images: ['https://i.pinimg.com/originals/c4/bb/10/c4bb10149e8f84c80c5ac52e0378cfdb.jpg'],
    },
    { 
        id: 35, 
        sports_name: 'Futsal',
        description: 'A variant of soccer played on a smaller, typically indoor field, with fewer players.',
        tickets: 'Available',
        series: 'Futsal World Cup',
        matches: 24,
        images: ['https://i.pinimg.com/originals/04/29/58/042958d21baf8721604a2e44a8346f12.jpg'],
    },
    { 
        id: 36, 
        sports_name: 'Synchronized Swimming',
        description: 'A team performance sport that combines swimming, dance, and gymnastics.',
        tickets: 'Available',
        series: 'FINA World Championships',
        matches: 16,
        images: ['https://i.pinimg.com/originals/05/1a/ed/051aed61eb5287b9e2be94c935679028.jpg'],
    },
    { 
        id: 37, 
        sports_name: 'Bobsleigh',
        description: 'A winter sport where teams of two or four make timed runs while traveling down narrow, twisting, banked, and downhill runs.',
        tickets: 'Available',
        series: 'IBSF World Championships',
        matches: 8,
        images: ['https://i.pinimg.com/originals/05/8f/07/058f070be0e912cc8eb88826a35ac4c2.jpg'],
    },
    { 
        id: 38, 
        sports_name: 'Luge',
        description: 'A winter sport in which one or two competitors make timed runs while traveling down narrow, twisting, banked, and downhill runs.',
        tickets: 'Available',
        series: 'FIL World Championships',
        matches: 6,
        images: ['https://i.pinimg.com/originals/d9/f4/0f/d9f40fa54a5f6e50e6476f517ea7c764.jpg'],
    },
    { 
        id: 39, 
        sports_name: 'Skeleton',
        description: 'A winter sliding sport in which an individual makes timed runs while traveling down narrow, twisting, banked, and downhill runs on a small sled.',
        tickets: 'Available',
        series: 'IBSF World Championships',
        matches: 4,
        images: ['https://i.pinimg.com/originals/9c/bc/67/9cbc67cdd62b4da46ef1d5d8f42bc084.jpg'],
    },
    { 
        id: 40, 
        sports_name: 'Curling',
        description: 'A sport in which players slide stones on a sheet of ice towards a target area, which is divided into four concentric circles.',
        tickets: 'Available',
        series: 'World Curling Federation Championships',
        matches: 12,
        images: ['https://i.pinimg.com/originals/8f/b1/54/8fb154c47448438c813c73a90d0b4c49.jpg'],
    },
    { 
        id: 41, 
        sports_name: 'Speed Skating',
        description: 'A competitive form of ice skating where participants race against each other in various distances.',
        tickets: 'Available',
        series: 'ISU World Cup',
        matches: 10,
        images: ['https://i.pinimg.com/originals/65/b2/cf/65b2cfb9c5d50c722649c9d1691f59b7.jpg'],
    },
    { 
        id: 42, 
        sports_name: 'Bandy',
        description: 'A team winter sport played on ice, similar to field hockey but with a ball instead of a puck.',
        tickets: 'Available',
        series: 'Bandy World Championships',
        matches: 8,
        images: ['https://i.pinimg.com/originals/67/1a/3e/671a3e50522de22ca6863a3b7201b97b.jpg'],
    },
    { 
        id: 43, 
        sports_name: 'Tug of War',
        description: 'A competition in which two teams pull on opposite ends of a rope, trying to pull the other team across a central line.',
        tickets: 'Available',
        series: 'Tug of War World Championships',
        matches: 5,
        images: ['https://i.pinimg.com/originals/70/74/4e/70744e251fc62b425dc300dc9c8ca204.jpg'],
    },
    { 
        id: 44, 
        sports_name: 'Parkour',
        description: 'An activity involving movement through environments, usually in an urban area, utilizing skills such as running, climbing, and jumping.',
        tickets: 'Available',
        series: 'Parkour World Cup',
        matches: 3,
        images: ['https://i.pinimg.com/originals/11/c6/3e/11c63e3cf1225c43c7e1b87668c453fa.jpg'],
    },
    { 
        id: 45, 
        sports_name: 'Skateboarding',
        description: 'An action sport involving riding and performing tricks on a skateboard.',
        tickets: 'Available',
        series: 'World Skate Championships',
        matches: 12,
        images: ['https://i.pinimg.com/originals/c3/8e/82/c38e82367b77bc13a1d41e162ef7ffec.jpg'],
    },
    { 
        id: 46, 
        sports_name: 'Surfing',
        description: 'The act of riding on the crest or along the tunnel of a wave, typically in the ocean.',
        tickets: 'Available',
        series: 'World Surf League',
        matches: 14,
        images: ['https://i.pinimg.com/originals/2f/d2/f8/2fd2f855774c0b7b8892e7b3769edc03.jpg'],
    },
    { 
        id: 47, 
        sports_name: 'Bodybuilding',
        description: 'A sport that focuses on physical fitness and aesthetic muscular development through weight training and nutrition.',
        tickets: 'Available',
        series: 'IFBB World Championships',
        matches: 8,
        images: ['https://i.pinimg.com/originals/f5/52/a5/f552a5c0469b4849d5fbe4e8db1ef645.jpg'],
    },
    { 
        id: 48, 
        sports_name: 'Sailing',
        description: 'A water sport that involves using boats or ships powered by sails.',
        tickets: 'Available',
        series: 'World Sailing Championships',
        matches: 6,
        images: ['https://i.pinimg.com/originals/67/32/f4/6732f458d23f465cb5fc5086ff35bb17.jpg'],
    },
    { 
        id: 49, 
        sports_name: 'Kite Surfing',
        description: 'A water sport that combines aspects of surfing and paragliding, using a board and a large kite.',
        tickets: 'Available',
        series: 'Kite Surfing World Cup',
        matches: 4,
        images: ['https://i.pinimg.com/originals/61/ae/53/61ae53e6fbc444adbb8fd3bba90ee1b1.jpg'],
    },
    { 
        id: 50, 
        sports_name: 'Horse Riding',
        description: 'The skill of riding, driving, or vaulting with horses, including competitive events.',
        tickets: 'Available',
        series: 'Equestrian World Championships',
        matches: 12,
        images: ['https://i.pinimg.com/originals/f1/72/62/f17262d0a5a7a45e4e9e8008a261b4c9.jpg'],
    },
];
